### ISSUE TITLE
"Channel credentials must be a ChannelCredentials object"

### ISSUE THREAD

**Issue by ardatan** [redhoyasa/grpc-reflection-js#6]
When you create a `ChannelCredentials` from `@grpc/grpc-js` but a different version using by `grpc-reflection-js` it gives `Channel credentials must be a ChannelCredentials object` error because of the `instanceof` check. So I think this package should have `@grpc/grpc-js` as a peer dependency or update its version.

**Comment by redhoyasa** [comment]
Please use version 0.1.2 for this
